// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using AVFoundation;
using CoreAnimation;

namespace Cyclorama.Views
{
	public partial class PerformanceView : NSView
	{
        AVPlayerLayer leftVideo, rightVideo;
        public AVPlayerLayer LeftVideo {
            get {
                return leftVideo;
            }
        }
        public AVPlayerLayer RightVideo {
            get {
                return rightVideo;
            }
        }

        public AVPlayer LeftPlayer { 
            get {
                return leftVideo.Player;
            }
            set {
                leftVideo.Player = value;
            }
        }

        public AVPlayer RightPlayer {
            get {
                return rightVideo.Player;
            }
            set {
                rightVideo.Player = value;
            }
        }

        public CALayer BackgroundLayer { get; set; }

		public PerformanceView (IntPtr handle) : base (handle)
		{
            BackgroundLayer = new CALayer ();
            BackgroundLayer.Name = "Background";

            leftVideo = new AVPlayerLayer ();
            leftVideo.Name = "leftVideo";

            rightVideo = new AVPlayerLayer ();
            rightVideo.Name = "rightVideo";
		}

        public override void ViewDidMoveToWindow ()
        {
            Layer.LayoutManager = CAConstraintLayoutManager.LayoutManager;

            BackgroundLayer.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MinX, "superlayer", CAConstraintAttribute.MinX));
            BackgroundLayer.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MinY, "superlayer", CAConstraintAttribute.MinY));
            BackgroundLayer.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MaxX, "superlayer", CAConstraintAttribute.MaxX));
            BackgroundLayer.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MaxY, "superlayer", CAConstraintAttribute.MaxY));
            Layer.AddSublayer (BackgroundLayer);

            leftVideo.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MinX, "superlayer", CAConstraintAttribute.MinX));
            leftVideo.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MinY, "superlayer", CAConstraintAttribute.MinY));
            leftVideo.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MaxX, "superlayer", CAConstraintAttribute.MaxX));
            leftVideo.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MaxY, "superlayer", CAConstraintAttribute.MaxY));
            Layer.AddSublayer (leftVideo);

            rightVideo.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MinX, "superlayer", CAConstraintAttribute.MinX));
            rightVideo.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MinY, "superlayer", CAConstraintAttribute.MinY));
            rightVideo.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MaxX, "superlayer", CAConstraintAttribute.MaxX));
            rightVideo.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MaxY, "superlayer", CAConstraintAttribute.MaxY));
            Layer.AddSublayer (rightVideo);

            base.ViewDidMoveToWindow ();
        }
	}
}
