// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using AVFoundation;
using CoreAnimation;

namespace Cyclorama.Views
{
	public partial class PerformanceView : NSView
	{
        AVPlayerLayer leftVideo, rightVideo;

        public AVPlayer LeftPlayer { 
            get {
                return leftVideo.Player;
            }
            set {
                leftVideo.Player = value;
            }
        }

        public AVPlayer RightPlayer {
            get {
                return rightVideo.Player;
            }
            set {
                rightVideo.Player = value;
            }
        }

		public PerformanceView (IntPtr handle) : base (handle)
		{
            leftVideo = new AVPlayerLayer ();
            leftVideo.Name = "leftVideo";

            rightVideo = new AVPlayerLayer ();
            rightVideo.Name = "rightVideo";

            rightVideo.Opacity = 0.5f;
		}

        public override void ViewDidMoveToWindow ()
        {
            Layer.LayoutManager = CAConstraintLayoutManager.LayoutManager;

            leftVideo.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MinX, "superlayer", CAConstraintAttribute.MinX));
            leftVideo.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MinY, "superlayer", CAConstraintAttribute.MinY));
            leftVideo.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MaxX, "superlayer", CAConstraintAttribute.MaxX));
            leftVideo.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MaxY, "superlayer", CAConstraintAttribute.MaxY));
            Layer.AddSublayer (leftVideo);

            rightVideo.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MinX, "superlayer", CAConstraintAttribute.MinX));
            rightVideo.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MinY, "superlayer", CAConstraintAttribute.MinY));
            rightVideo.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MaxX, "superlayer", CAConstraintAttribute.MaxX));
            rightVideo.AddConstraint (CAConstraint.Create (CAConstraintAttribute.MaxY, "superlayer", CAConstraintAttribute.MaxY));
            Layer.AddSublayer (rightVideo);

            base.ViewDidMoveToWindow ();
        }

        public float CrossfaderPosition {
            get { return rightVideo.Opacity; }
            set { rightVideo.Opacity = value; }
        }
	}
}
