// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

using AVFoundation;
using AVKit;

namespace Cyclorama
{
	public partial class PlaybackPreviewView : AVPlayerView
    {
		public PlaybackPreviewView (IntPtr handle) : base (handle)
		{
            ControlsStyle = AVPlayerViewControlsStyle.None;
		}
	}
}
